name: "Manual Approval"
on:
  workflow_dispatch:
        
jobs:
  build-plan:
    name: Approval
    runs-on: ubuntu-latest
        
    steps:
      - name: Simulate Approval Step
        run: echo "Manual approval testing"

      - name: Approval
        uses: trstringer/manual-approval@v1
        with:
          approvers: venkatkumarp
          minimum-approvals: 1
          secret: ${{ secrets.GITHUB_TOKEN }}
